var width, height;
var username;
width = 10.5;
height = 20;
username = "Hash";
var area = width * height;
console.log("Area of rectangle is: ".concat(area));
console.log("Auto generated by: " + username);
