let width, height: number;
let username: String;

width = 10.5;
height = 20;

username = `Hash`
let area : number = width*height;

console.log(`Area of rectangle is: ${area}`);
console.log(`Auto generated by: ` + username);